name: Check PR health

on: [pull_request]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install packages
      run: yarn
    
    - name: Check linting
      run: yarn lint
